name: "Install_deps"
description: "Installs the dependencies, checks out the code and sets up caching"

runs:
  using: "composite"
  steps:
    - name: Update repos
      shell: bash
      run: sudo apt-get update
    - name: Upgrade system
      shell: bash
      run: sudo apt-get upgrade -y
    - name: Install libwayland
      shell: bash
      run: sudo apt-get install -y libwayland-dev
